=== EricHuangCN/ExMobiBeginnerBook/code/helloworld/server/maxml-2.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			targetNamespace="http://www.nj.fiberhome.com.cn/map"
			xmlns:fh="http://www.nj.fiberhome.com.cn/map" 
			elementFormDefault="qualified"> 
	
	<!-- 根节点 -->
	<xsd:element name="maxml">
	   <xsd:complexType>
	      <xsd:sequence>
	         <xsd:group ref="fh:maxmlGroup"  minOccurs="0" maxOccurs="unbounded"/>
	      </xsd:sequence>
	      <xsd:attribute name="version" type="xsd:string" fixed="2.0" use="required">
	      </xsd:attribute>
	   </xsd:complexType>
	   <xsd:unique name="baseaddr">
			<xsd:selector xpath="fh:route"></xsd:selector>
			<xsd:field xpath="@baseaddr"></xsd:field>
		</xsd:unique>
	</xsd:element>
	
	<!-- maxml子节点组 -->
	<xsd:group name="maxmlGroup">
		<xsd:choice>
			<xsd:element name="route" type="fh:routeType" minOccurs="0" maxOccurs="unbounded">
				<xsd:unique name="pattern">
					<xsd:selector xpath="fh:forward"></xsd:selector>
					<xsd:field xpath="@pattern"></xsd:field>
				</xsd:unique>
			</xsd:element>
	      	<xsd:element name="config" type="fh:configType" minOccurs="0" maxOccurs="1">
	      		<xsd:unique name="mimetype">
					<xsd:selector xpath="fh:mimetype"></xsd:selector>
					<xsd:field xpath="@contenttype"></xsd:field>
				</xsd:unique>
				<xsd:unique name="domain">
					<xsd:selector xpath="fh:domain"></xsd:selector>
					<xsd:field xpath="@name"></xsd:field>
				</xsd:unique>
				<xsd:unique name="database">
					<xsd:selector xpath="fh:database"></xsd:selector>
					<xsd:field xpath="@id"></xsd:field>
				</xsd:unique>
	      	</xsd:element>
	      	<xsd:element name="pushchannels" type="fh:pushchannelsType" minOccurs="0" maxOccurs="1">
	      		<xsd:unique name="pushchannel">
					<xsd:selector xpath="fh:pushchannel"></xsd:selector>
					<xsd:field xpath="@id"></xsd:field>
				</xsd:unique>
	      	</xsd:element>
	      	<xsd:element name="services" type="fh:ServiceType" minOccurs="0" maxOccurs="1"/>
		</xsd:choice>
	</xsd:group>
	
	<!-- 路由配置 -->
	<xsd:complexType name="routeType">
		<xsd:annotation>
			<xsd:documentation xml:lang="zh">
				转向路由
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="forward" type="fh:forwardType" maxOccurs="unbounded" minOccurs="0" >
				
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="baseaddr" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation xml:lang="zh">
					目标转向前缀地址
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>
	
	<!-- 跳转forward节点 -->
	<xsd:complexType name="forwardType">
		<xsd:annotation>
			<xsd:documentation xml:lang="zh">
				forward跳转指向
			</xsd:documentation>
		</xsd:annotation>
		<xsd:attribute name="pattern" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation xml:lang="zh">
					目标转向相对地址
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="path" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation xml:lang="zh">
					指定的跳转页面
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>
	
	<!-- 推送节点 -->
	<xsd:complexType name="pushchannelsType">
		<xsd:sequence>
			<xsd:element name="pushchannel" type="fh:pushchannelType" maxOccurs="unbounded" minOccurs="0"/>
		</xsd:sequence>	
		<xsd:attribute name="authpage" type="xsd:string" >
			<xsd:annotation>
				<xsd:documentation xml:lang="zh">
					鉴权页面
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>
	
	<xsd:complexType name="pushchannelType">
		<xsd:annotation>
			<xsd:documentation>
				推送频道配置
			</xsd:documentation>
		</xsd:annotation>
		<xsd:all>
			<xsd:element name="cron" type="fh:cronType"  maxOccurs="1" minOccurs="0"/>
		</xsd:all>
		<xsd:attribute name="id" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation xml:lang="zh">
					推送频道唯一标识
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="name" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation xml:lang="zh">
					推送频道名称
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="description" type="xsd:string">
			<xsd:annotation>
				<xsd:documentation xml:lang="zh">
					频道描述
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="path" type="xsd:string">
			<xsd:annotation>
				<xsd:documentation xml:lang="zh">
					处理推送业务的目标地址
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="needsubscribed" type="fh:booleanType">
			<xsd:annotation>
				<xsd:documentation xml:lang="zh">
					是否需要订阅
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>
	
	<xsd:simpleType name="booleanType">
	   <xsd:restriction  base="xsd:string">
	      <xsd:enumeration value="true" />
	      <xsd:enumeration value="false" />
	   </xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="sessionTypeE">
	   <xsd:restriction  base="xsd:string">
	   	  <xsd:enumeration value="stateless" />
	      <xsd:enumeration value="stateful" />
	   </xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="levelType">
	   <xsd:restriction  base="xsd:string">
	   	  <xsd:enumeration value="debug" />
	      <xsd:enumeration value="info" />
	      <xsd:enumeration value="error" />
	   </xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="cronType" mixed="true">
		<xsd:annotation>
			<xsd:documentation>
				推送调度策略
			</xsd:documentation>
		</xsd:annotation>
		<xsd:attribute name="starttime" type="xsd:string" use="optional">
			<xsd:annotation>
				<xsd:documentation>
					推送调度开始时间
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="endtime" type="xsd:string" use="optional">
			<xsd:annotation>
				<xsd:documentation>
					推送调度结束时间
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>

	<!-- 调度参数 -->
	<xsd:complexType name="paramtersType" mixed="true">
		<xsd:annotation>
			<xsd:documentation>
				推送调度参数
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:any processContents="skip"  minOccurs="0" maxOccurs="unbounded">
			</xsd:any>
		</xsd:sequence>
	</xsd:complexType>

	<!-- 应用配置节点 -->
	<xsd:complexType name="configType">
		<xsd:annotation>
			<xsd:documentation xml:lang="zh">
				应用配置
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:group ref="fh:configGroup"  maxOccurs="unbounded" minOccurs="0" />
		</xsd:sequence>
	</xsd:complexType>
	
	<!-- 配置组 -->
	<xsd:group name="configGroup">
		<xsd:choice>
			<xsd:element name="database" type="fh:databaseType" maxOccurs="unbounded" minOccurs="0" />
			<xsd:element name="timer" type="fh:timerType" maxOccurs="unbounded" minOccurs="0" />
			<xsd:element name="mimetype" type="fh:mimetypeType" maxOccurs="unbounded" minOccurs="0" />
			<xsd:element name="proxy" type="fh:proxyType" maxOccurs="1" minOccurs="0" />
			<xsd:element name="domain" type="fh:domainType" maxOccurs="unbounded" minOccurs="0" />
			<xsd:element name="session" type="fh:sessionType"  maxOccurs="1" minOccurs="0" />
			<xsd:element name="cachepolicy" type="fh:cacheType"  maxOccurs="1" minOccurs="0" />
			<xsd:element name="applogconfig" type="fh:logType"  maxOccurs="1" minOccurs="0" />
			<xsd:element name="apptimeout" type="fh:appTimeOutType"  maxOccurs="1" minOccurs="0" />
			<xsd:element name="htmlformat" type="fh:htmlformatType"  maxOccurs="1" minOccurs="0" />
		</xsd:choice>
	</xsd:group>
	
	
	
	<!-- 数据库配置节点 -->
	<xsd:complexType name="databaseType">
		<xsd:annotation>
			<xsd:documentation>
				数据库配置
			</xsd:documentation>
		</xsd:annotation>
		<xsd:attribute name="id" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation xml:lang="zh">
					数据库唯一标识
					</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="driver" type="xsd:string" use="optional">
			<xsd:annotation>
				<xsd:documentation xml:lang="zh">
					数据库使用驱动
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attributeGroup ref="fh:urlGroup"/>
		<xsd:attribute name="url" type="xsd:string" use="optional">
			<xsd:annotation>
				<xsd:documentation xml:lang="zh">
					数据库的连接地址
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="user" type="xsd:string" use="required" >
			<xsd:annotation>
				<xsd:documentation xml:lang="zh">
					数据库用户名
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="password" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation xml:lang="zh">
					数据库密码
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="maxconn" type="xsd:string" use="optional">
			<xsd:annotation>
				<xsd:documentation xml:lang="zh">
					最大连接数
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="minconn" type="xsd:int" use="optional">
			<xsd:annotation>
				<xsd:documentation xml:lang="zh">
					最小连接数
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="defconn" type="xsd:int" use="optional">
			<xsd:annotation>
				<xsd:documentation xml:lang="zh">
					默认连接数
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="heartsql" type="xsd:string" use="optional">
			<xsd:annotation>
				<xsd:documentation xml:lang="zh">
					心跳sql语句
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>
	
	<xsd:attributeGroup name="urlGroup">
		<xsd:attribute name="ip" type="xsd:string" use="optional" >
			<xsd:annotation>
				<xsd:documentation xml:lang="zh">
					数据库的连接ip地址
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="port" type="xsd:integer" use="optional">
			<xsd:annotation>
				<xsd:documentation xml:lang="zh">
					数据库的连接端口号
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="dbname" type="xsd:string" use="optional">
			<xsd:annotation>
				<xsd:documentation xml:lang="zh">
					数据库名
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="dbtype" type="fh:dbType" use="optional">
			<xsd:annotation>
				<xsd:documentation xml:lang="zh">
					数据库类型
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:attributeGroup>
	
	<xsd:simpleType name="dbType">
	   <xsd:restriction  base="xsd:string">
	      <xsd:enumeration value="oracle" />
	      <xsd:enumeration value="mysql" />
	      <xsd:enumeration value="postgresql" />
	      <xsd:enumeration value="db2" />
	      <xsd:enumeration value="mssqlserver" />
	   </xsd:restriction>
	</xsd:simpleType>
	
	
	<!-- 定时器配置节点 -->
	<xsd:complexType name="timerType">
		<xsd:annotation>
			<xsd:documentation>
				数据库配置
			</xsd:documentation>
		</xsd:annotation>
		<xsd:attribute name="starttime" type="xsd:string">
			<xsd:annotation>
				<xsd:documentation>
					定时器开始时间
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="endtime" type="xsd:string">
			<xsd:annotation>
				<xsd:documentation>
					定时器结束时间
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="delay" type="xsd:int">
			<xsd:annotation>
				<xsd:documentation>
					定时器延时执行时间（单位：分钟）
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="period" type="xsd:int" use="required">
			<xsd:annotation>
				<xsd:documentation>
					定时器间隔执行时间（单位：分钟）
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="path" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation>
					执行任务目标地址
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>
	
	<xsd:complexType name="mimetypeType">
		<xsd:annotation>
			<xsd:documentation>
				多媒体配置
			</xsd:documentation>
		</xsd:annotation>
		<xsd:attribute name="contenttype" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation>
					文档数据类型
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="extension" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation>
					文档扩展名
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>


	<xsd:complexType name="proxyType">
		<xsd:annotation>
			<xsd:documentation>
				代理服务配置
			</xsd:documentation>
		</xsd:annotation>
		<xsd:attribute name="ip" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation>
					代理服务IP地址
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="port" type="xsd:int" use="required">
			<xsd:annotation>
				<xsd:documentation>
					代理服务端口号
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="username" type="xsd:string" use="optional">
			<xsd:annotation>
				<xsd:documentation>
					用户名
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="password" type="xsd:string" use="optional">
			<xsd:annotation>
				<xsd:documentation>
					密码
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>
	
	<xsd:complexType name="domainType">
		<xsd:annotation>
			<xsd:documentation>
				自定义域名配置
			</xsd:documentation>
		</xsd:annotation>
		<xsd:attribute name="name"  use="required">
			<xsd:annotation>
				<xsd:documentation>
					自定义域名
				</xsd:documentation>
			</xsd:annotation>
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:pattern value="[A-Za-z0-9_\.\-]+" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="address" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation>
					服务实际地址
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>	
	
	<xsd:complexType name="sessionType">
		<xsd:attribute name="type" type="fh:sessionTypeE" use="required">
			<xsd:annotation>
				<xsd:documentation>
					session状态
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>
	
	<xsd:complexType name="cacheType">
		<xsd:attribute name="preview" type="fh:booleanType">
			<xsd:annotation>
				<xsd:documentation>
					下载缓存是否有效
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="download" type="fh:booleanType">
			<xsd:annotation>
				<xsd:documentation>
					预览缓存是否有效
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="days" type="xsd:int">
			<xsd:annotation>
				<xsd:documentation>
					应用级缓存有效时间 单位：天
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>
	
	
	<xsd:complexType name="logType">
		<xsd:attribute name="threshold" type="fh:levelType">
			<xsd:annotation>
				<xsd:documentation>
					日志级别
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="maxfilesize" type="xsd:int">
			<xsd:annotation>
				<xsd:documentation>
					日志单个文件大小 单位：M
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="maxbackupindex" type="xsd:int">
			<xsd:annotation>
				<xsd:documentation>
					日志保留文件数目
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>
	
	
	<xsd:complexType name="appTimeOutType">
		<xsd:attribute name="appexpireminute" type="xsd:int" use="required">
			<xsd:annotation>
				<xsd:documentation>
					会话过期时间，单位：分钟。
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>
	
	<xsd:complexType name="ServiceType">
		<xsd:annotation>
			<xsd:documentation xml:lang="zh">
				应用服务节点
			</xsd:documentation>
		</xsd:annotation>
		<xsd:all>
			<xsd:element name="http-service" type="fh:httpServiceType" maxOccurs="1" minOccurs="0" >
				<xsd:unique name="http-service-pattern">
					<xsd:selector xpath="fh:forward"></xsd:selector>
					<xsd:field xpath="@pattern"></xsd:field>
				</xsd:unique>
			</xsd:element>
			<xsd:element name="ws-service" type="fh:ws-serviceType" maxOccurs="1" minOccurs="0" >
			</xsd:element>
		</xsd:all>
	</xsd:complexType>
	
	<!-- httpservice -->
	<xsd:complexType name="httpServiceType">
		<xsd:annotation>
			<xsd:documentation xml:lang="zh">
				httpservice配置
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="forward" type="fh:forwardType" maxOccurs="unbounded" minOccurs="0" >
				
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="ws-serviceType">
		<xsd:annotation>
			<xsd:documentation xml:lang="zh">
				ws-service配置
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="wsservice" type="fh:wsserviceType" maxOccurs="unbounded" minOccurs="0" >
				
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	
	<!-- wsservice -->
	<xsd:complexType name="wsserviceType">
		<xsd:annotation>
			<xsd:documentation xml:lang="zh">
				wsservice配置
			</xsd:documentation>
		</xsd:annotation>
		<xsd:attribute name="interface" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation xml:lang="zh">
					接口名称
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="operation" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation xml:lang="zh">
					方法名称
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="path" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation xml:lang="zh">
					触发的jsp路径
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>
	
	<!-- htmlformat -->
	<xsd:complexType name="htmlformatType">
		<xsd:attribute name="wellformat" type="xsd:boolean" use="optional"
			default="false">
			<xsd:annotation>
				<xsd:documentation xml:lang="zh">
					是否做格式规范化
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>
</xsd:schema>

=== EricHuangCN/ExMobiBeginnerBook/code/pushdemo/server/mapp.xml
<?xml version="1.0" encoding="UTF-8" ?>
<maxml version="2.0" xmlns="http://www.nj.fiberhome.com.cn/map"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.nj.fiberhome.com.cn/map maxml-2.0.xsd">
	<config>
    	<htmlformat wellformat="true" />
    	<!-- 配置伪域名 -->
    	<domain address="218.94.117.235:1001" name="oa"/>
    	<!-- 配置数据库连接参数 -->
    	<database id="postgresql" dbtype="postgresql" ip="218.94.117.235" port="1006" dbname="app" user="sitest" password="123456" maxconn="10" minconn="2" defconn="5" />
  	</config>
  	<route baseaddr="http://oa">
  	
  		<!-- form的ajax提交 -->
		<forward pattern="/app/template/checkLogin.jsp" path="mCheckLogin.jsp"/>
  	
  	</route>
  	
  	<services>
  		<!-- http-service用于发布http接口 -->
  		<http-service>
  			<!-- 每一个接口对应一个forward配置，
  			其中pattern是接口的被调用的名称，完整的调用地址为:http://{ip}:{port}/process/notify/{appid}/{pattern}
  			所以针对此配置，本机的调用接口应该为http://127.0.0.1:8001/process/notify/pushdemo/itask
  			调用接口的时候可以传递一些参数，参数可以在url中也可以在请求头或者请求正文中，参数可以是键值对也可以是非键值对
  			path是当接口被调用时服务端的处理JSP地址，在JSP中就可以获取调用接口时传递的参数 -->
  			<forward pattern="/itask" path="push/itask.jsp"/> 		
  		</http-service>
  	
  	</services>
</maxml>

=== EricHuangCN/ExMobiBeginnerBook/code/dbdemo/server/mapp.xml
<?xml version="1.0" encoding="UTF-8" ?>
<maxml version="2.0" xmlns="http://www.nj.fiberhome.com.cn/map"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.nj.fiberhome.com.cn/map maxml-2.0.xsd">
	<config>
		<database id="postgresql" dbtype="postgresql" ip="218.94.117.235" port="1006" dbname="app" user="sitest" password="123456" maxconn="10" minconn="2" defconn="5" />	
	</config>
	
	<route baseaddr="http://sql">
		<!-- 查询操作 -->
		<forward pattern="/query.jsp.*" path="dbQuery.jsp"/>
		<!-- 显示详情 -->
		<forward pattern="/show.jsp.*" path="dbShow.jsp"/>
		<!-- 更新操作 -->
		<forward pattern="/update.jsp" path="dbUpdate.jsp"/>
		<!-- 删除操作 -->
		<forward pattern="/delete.jsp.*" path="dbDelete.jsp"/>
		<!-- 插入操作 -->
		<forward pattern="/insert.jsp.*" path="dbInsert.jsp"/>
		<!-- 获取第一条数据 -->
		<forward pattern="/getFirstData.jsp" path="dbFirstData.jsp"/>
	</route>
</maxml>

=== EricHuangCN/ExMobiBeginnerBook/code/oademo/server/mapp.xml
<?xml version="1.0" encoding="UTF-8" ?>
<maxml version="2.0" xmlns="http://www.nj.fiberhome.com.cn/map"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.nj.fiberhome.com.cn/map maxml-2.0.xsd">
	<config>
    	<htmlformat wellformat="true" />
    	<!-- 配置伪域名 -->
    	<domain address="218.94.117.235:1001" name="oa"/>
  	</config>
  	<!-- 配置route路由，如果有多个域名可以配置多个route -->
  	<route baseaddr="http://oa">
  		<!-- 此处配置客户端URL请求的处理JSP文件，pattern是匹配URL的正则表达式，path是对用的服务端的JSP文件名 -->
  		
  		<!-- 登陆页面get -->
		<forward pattern="/app/template/login.jsp" path="mLogin.jsp"/>	
  	
  		<!-- 登陆校验post带键值对 -->
		<forward pattern="/app/template/checkLogin.jsp" path="mCheckLogin.jsp"/>
		
		<!-- 任务创建get -->
		<forward pattern="/app/template/jsp/addTask.jsp" path="mAddTask.jsp"/>
		
		<!-- 保存任务post带附件 -->
		<forward pattern="/app/template/action/taskManagerAction.jsp\?handler=save" path="mTaskManager.jsp"/>
		
		<!-- 列表展示post带XML请求体 -->
		<forward pattern="/app/template/action/taskManagerAction.jsp\?handler=list&amp;dataType=xml.*" path="mTaskManagerListXML.jsp"/>
		
  		<!-- 新建信息页面 -->
		<forward pattern="/app/template/jsp/newInfo.jsp" path="mNewInfo.jsp"/>
		
		<!-- 发送信息页面 -->
		<forward pattern="/app/allInOne.jsp" path="mAllInOne.jsp"/>
		
  		
  	</route>
</maxml>
